
services:
  app:
    build: .
    container_name: service-orders
    ports:
      - "3000:3000"
    # environment:
    #   DB_HOST: db
    #   DB_USER: root
    #   DB_PASSWORD: example
    #   DB_NAME: service_orders
    # depends_on:
    #   - db

#   db:
#     image: mysql:8.0
#     container_name: mysql-db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#       MYSQL_DATABASE: service_orders
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
